# Generated by Django 5.2.8 on 2025-12-28 02:37

import core.fields
import django.db.models.deletion
import taggit.managers
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('excerpt', models.CharField(max_length=140)),
                ('body', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('A', 'Archived'), ('D', 'Drafted'), ('P', 'Published')], default='P', max_length=1)),
                ('publication_time', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('last_modify_time', models.DateTimeField(auto_now=True, verbose_name='Modify time')),
                ('category', models.CharField(max_length=30)),
                ('color', core.fields.HexColorField(max_length=7, verbose_name='Banner color')),
                ('slug', models.SlugField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publication_time'],
            },
        ),
    ]
